<!DOCTYPE html>
<html lang='en'>

  <head>
    <meta charset='UTF-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>Document</title>
    <link rel='icon' href='data:,' />

    <link rel="stylesheet" href="css/site/home.css">
  </head>

  <body>
    <img src="img/site/quickstart.png" alt="quickstart banner">
    <h1>This Is the home page</h1>
    <?= DB_TYPE ?>
    <br>
    <button id="btn">CLICK ME</button>
    <p id="demo"></p>

    <script src="js/site/home.js"></script>
  </body>

</html>